os: linux

language: node_js

node_js:
  - 12.14.0

branches:
  only:
    - master

jobs:
  include:
    - script:
        - mkdir web
        - mv index.html web/index.html
        - cd web
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: false
        edge: true
        commit_message: 'Deploy Travis CI to %{target_branch} branch'
        'on':
          branch: master
